export const ChangePassword="ChangePassword"
export const EditUser="EditUser"
export const AddUser="AddUser"
export const ConUser="ConUser"
export const EditCompany="EditCompany"
export const AddCash="AddCash"
export const UpdateCurrencies="UpdateCurrencies"
export const AddChq="AddChq"
export const EditChq="EditChq"
export const RemoveChq="RemoveChq"
export const AddElement="AddElement"
export const AddDep="AddDep"
export const EditDep="EditDep"
export const RemoveDep="RemoveDep"
export const AddInvoice="AddInvoice"
export const Add="Add"
  