let initState = [
    {value:'ABC BANK',label:'ABC BANK'},
    {value:'ALBARAKA BANK',label:'ALBARAKA BANK'},
    {value:'ALWIFEK BANK',label:'ALWIFEK BANK'},
    {value:'AMEN BANK',label:'AMEN BANK'},
    {value:'ATB - ARAB TUNISIAN BANK',label:'ATB - ARAB TUNISIAN BANK'},
    {value:'ATTIJARI BANK',label:'ATTIJARI BANK'},
    {value:'BFPME - BANQUE FINANCEMENT PET. ET MOY. ENTREPRISES',label:'BFPME - BANQUE FINANCEMENT PET. ET MOY. ENTREPRISES'},
    {value:'BFT - BANQUE FRANCO-TUNISIENNE',label:'BFT - BANQUE FRANCO-TUNISIENNE'},
    {value:'BH - BANQUE D HABITAT',label:'BH - BANQUE D HABITAT'},
    {value:'BIAT - BANQUE INTERNATIONALE ARABE DE TUNISIE',label:'BIAT - BANQUE INTERNATIONALE ARABE DE TUNISIE'},
    {value:'BNA - BANQUE NATIONALE AGRICOLE',label:'BNA - BANQUE NATIONALE AGRICOLE'},
    {value:'BT - BANQUE DE TUNISIE',label:'BT - BANQUE DE TUNISIE'},
    {value:'BTE - BANQUE DE TUNISIE ET DES EMIRATS',label:'BTE - BANQUE DE TUNISIE ET DES EMIRATS'},
    {value:'BTK - BANQUE TUNISO-KOWEITIENNE',label:'BTK - BANQUE TUNISO-KOWEITIENNE'},
    {value:'BTL - BANQUE TUNISO-LIBYENNE',label:'BTL - BANQUE TUNISO-LIBYENNE'},
    {value:'BTS - BANQUE TUNISIENNE DE SOLIDARITE',label:'BTS - BANQUE TUNISIENNE DE SOLIDARITE'},
    {value:'BZ - BANQUE ZITOUNA',label:'BZ - BANQUE ZITOUNA'},
    {value:'CITI-BANK TUNIS BRANCH ONSHORE',label:'CITI-BANK TUNIS BRANCH ONSHORE'},
    {value:'LA POSTE TUNISIENNE',label:'LA POSTE TUNISIENNE'},
    {value:'NORTH AFRICA INTERNATIONAL BANK',label:'NORTH AFRICA INTERNATIONAL BANK'},
    {value:'QNB - QATAR NATIONAL BANK TUNISIA',label:'QNB - QATAR NATIONAL BANK TUNISIA'},
    {value:'STB - SOCIETE TUNISIENNE DE BANQUE',label:'STB - SOCIETE TUNISIENNE DE BANQUE'},
    {value:'STUSID BANK',label:'STUSID BANK'},
    {value:'TIB - TUNISIAN INTERNATIONAL BANK',label:'TIB - TUNISIAN INTERNATIONAL BANK'},
    {value:'TQB - TUNISIAN QATARI BANK',label:'TQB - TUNISIAN QATARI BANK'},
    {value:'UBCI - UNION BANCAIRE COMMERCE ET INDUSTRIE',label:'UBCI - UNION BANCAIRE COMMERCE ET INDUSTRIE'},
    {value:'UIB - UNION INTERNATIONALE DE BANQUES',label:'UIB - UNION INTERNATIONALE DE BANQUES'},
    
  ]
    const BankReducer = (state=initState, action) => {
        switch (action.type) {
            case "": return{
  
            }
            
             default :return state;
        }
    
    };

export default BankReducer